apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-base
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: php-apache
        image: mouhamed888/ligne-rouge-web
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: root
        - name: DATABASE_NAME
          value: redline
      volumes:
      - name: app-volume
        emptyDir: {}
